In [ ]:
import pandas as pd
df = pd.read_csv("/Users/edwind/Desktop/statinf_project/python_code/data/departures_chalmers_snapshots.csv")
df.head()

,collected_at,service_journey_gid,line,line_short_name,line_designation,line_name,transport_mode,direction,stop_point_gid,stop_point_name,platform,realtime_platform,planned_time,estimated_time,best_time,is_cancelled,is_part_cancelled,departure_key
0,2026-03-08T21:12:32+01:00,9015014500605551,6,6,6,Spårvagn 6,tram,Kortedala via Centralstationen,9022014001960001,"Chalmers, Göteborg",A,NaN,2026-03-08T21:12:00.0000000+01:00,2026-03-08T21:14:00.0000000+01:00,2026-03-08T21:14:00.0000000+01:00,False,False,9015014500605551|9022014001960001|2026-03-08T2...
1,2026-03-08T21:12:32+01:00,9015014506400709,64,64,64,Buss 64,bus,"Heden, Påstigning fram",9022014001960003,"Chalmers, Göteborg",C,NaN,2026-03-08T21:15:00.0000000+01:00,2026-03-08T21:15:00.0000000+01:00,2026-03-08T21:15:00.0000000+01:00,False,False,9015014506400709|9022014001960003|2026-03-08T2...
2,2026-03-08T21:12:32+01:00,9015014506400710,64,64,64,Buss 64,bus,"Högsbohöjd, Påstigning fram",9022014001960004,"Chalmers, Göteborg",D,NaN,2026-03-08T21:18:00.0000000+01:00,2026-03-08T21:20:00.0000000+01:00,2026-03-08T21:20:00.0000000+01:00,False,False,9015014506400710|9022014001960004|2026-03-08T2...
3,2026-03-08T21:12:32+01:00,9015014500605602,6,6,6,Spårvagn 6,tram,Länsmansgården via Sahlgrenska,9022014001960002,"Chalmers, Göteborg",B,NaN,2026-03-08T21:23:00.0000000+01:00,2026-03-08T21:29:00.0000000+01:00,2026-03-08T21:29:00.0000000+01:00,False,False,9015014500605602|9022014001960002|2026-03-08T2...
4,2026-03-08T21:12:32+01:00,9015014500605575,6,6,6,Spårvagn 6,tram,Kortedala via Centralstationen,9022014001960001,"Chalmers, Göteborg",A,NaN,2026-03-08T21:27:00.0000000+01:00,2026-03-08T21:30:00.0000000+01:00,2026-03-08T21:30:00.0000000+01:00,False,False,9015014500605575|9022014001960001|2026-03-08T2...

In [1]:
import csv

with open("data/data.txt") as fin, open("data/data.csv", "w", newline="") as fout:
    reader = csv.reader(fin, delimiter="\t")
    writer = csv.writer(fout)
    writer.writerow(["collected_at", "line", "transport_mode", "planned_time", "estimated_time"])
    writer.writerows(reader)

In [19]:
import pandas as pd
df = pd.read_csv("/Users/edwind/Desktop/statinf_project/python_code/data/data.csv")
df.head()

,collected_at,line,transport_mode,planned_time,estimated_time
0,2026-03-09 06:33:25,6,Spårvagn,2026-03-09T06:31:00.0000000+01:00,2026-03-09T06:33:00.0000000+01:00
1,2026-03-09 06:33:25,64,Spårvagn,2026-03-09T06:28:00.0000000+01:00,2026-03-09T06:35:00.0000000+01:00
2,2026-03-09 06:33:25,753,Spårvagn,2026-03-09T06:31:00.0000000+01:00,2026-03-09T06:35:00.0000000+01:00
3,2026-03-09 06:33:25,64,Spårvagn,2026-03-09T06:36:00.0000000+01:00,2026-03-09T06:35:00.0000000+01:00
4,2026-03-09 06:33:25,6,Spårvagn,2026-03-09T06:19:00.0000000+01:00,2026-03-09T06:36:00.0000000+01:00

In [20]:
df.drop("transport_mode", axis=1, inplace=True) # We only have one transport mode, so this column is not useful for our analysis.
df.head()

,collected_at,line,planned_time,estimated_time
0,2026-03-09 06:33:25,6,2026-03-09T06:31:00.0000000+01:00,2026-03-09T06:33:00.0000000+01:00
1,2026-03-09 06:33:25,64,2026-03-09T06:28:00.0000000+01:00,2026-03-09T06:35:00.0000000+01:00
2,2026-03-09 06:33:25,753,2026-03-09T06:31:00.0000000+01:00,2026-03-09T06:35:00.0000000+01:00
3,2026-03-09 06:33:25,64,2026-03-09T06:36:00.0000000+01:00,2026-03-09T06:35:00.0000000+01:00
4,2026-03-09 06:33:25,6,2026-03-09T06:19:00.0000000+01:00,2026-03-09T06:36:00.0000000+01:00

In [21]:
# Clean up planned_time and estimated_time columns by converting them to datetime objects.
df["planned_time"] = pd.to_datetime(df["planned_time"])
df["estimated_time"] = pd.to_datetime(df["estimated_time"])
df.head()

,collected_at,line,planned_time,estimated_time
0,2026-03-09 06:33:25,6,2026-03-09 06:31:00+01:00,2026-03-09 06:33:00+01:00
1,2026-03-09 06:33:25,64,2026-03-09 06:28:00+01:00,2026-03-09 06:35:00+01:00
2,2026-03-09 06:33:25,753,2026-03-09 06:31:00+01:00,2026-03-09 06:35:00+01:00
3,2026-03-09 06:33:25,64,2026-03-09 06:36:00+01:00,2026-03-09 06:35:00+01:00
4,2026-03-09 06:33:25,6,2026-03-09 06:19:00+01:00,2026-03-09 06:36:00+01:00

In [22]:
# Each time is on the same day and all en in +01:00 timezone
# So let's only keep exact times
df["planned_time"] = df["planned_time"].dt.time
df["estimated_time"] = df["estimated_time"].dt.time
df.head()

          collected_at  line planned_time estimated_time
0  2026-03-09 06:33:25     6     06:31:00       06:33:00
1  2026-03-09 06:33:25    64     06:28:00       06:35:00
2  2026-03-09 06:33:25   753     06:31:00       06:35:00
3  2026-03-09 06:33:25    64     06:36:00       06:35:00
4  2026-03-09 06:33:25     6     06:19:00       06:36:00

In [36]:
df_6 = df[df["line"] == 6]
df_6_cleaned = df_6.drop_duplicates(subset=["planned_time"], keep="last")
# df_6
df_6_cleaned

            collected_at  line planned_time estimated_time
0    2026-03-09 06:33:25     6     06:31:00       06:33:00
10   2026-03-09 06:38:26     6     06:19:00       06:38:00
11   2026-03-09 06:38:26     6     06:35:00       06:39:00
30   2026-03-09 06:48:27     6     06:43:00       06:48:00
33   2026-03-09 06:48:27     6     06:48:00       06:50:00
52   2026-03-09 06:58:27     6     06:56:00       07:00:00
73   2026-03-09 07:08:28     6     07:01:00       07:09:00
76   2026-03-09 07:08:28     6     07:06:00       07:11:00
83   2026-03-09 07:13:29     6     07:11:00       07:16:00
98   2026-03-09 07:18:29     6     07:16:00       07:21:00
99   2026-03-09 07:18:29     6     07:19:00       07:22:00
114  2026-03-09 07:28:30     6     07:28:00       07:30:00
120  2026-03-09 07:33:30     6     07:27:00       07:34:00
133  2026-03-09 07:38:31     6     07:36:00       07:39:00
140  2026-03-09 07:43:31     6     07:37:00       07:44:00
143  2026-03-09 07:43:31     6     07:45:00       07:46:00
150  2026-03-09 07:48:32     6     07:44:00       07:48:00
171  2026-03-09 07:58:33     6     07:53:00       07:59:00
177  2026-03-09 07:58:33     6     08:00:00       08:01:00
182  2026-03-09 08:03:33     6     08:01:00       08:04:00
194  2026-03-09 08:08:34     6     08:09:00       08:11:00
203  2026-03-09 08:13:34     6     08:08:00       08:16:00
214  2026-03-09 08:18:35     6     08:16:00       08:21:00
225  2026-03-09 08:23:35     6     08:17:00       08:26:00
226  2026-03-09 08:23:35     6     08:24:00       08:26:00
246  2026-03-09 08:33:36     6     08:33:00       08:36:00
251  2026-03-09 08:38:36     6     08:25:00       08:40:00
261  2026-03-09 08:43:37     6     08:43:00       08:43:00
282  2026-03-09 08:53:38     6     08:53:00       08:53:00
283  2026-03-09 08:53:38     6     08:44:00       08:56:00
300  2026-03-09 09:03:38     6     08:54:00       09:03:00
316  2026-03-09 09:08:38     6     09:03:00       09:11:00
330  2026-03-09 09:18:39     6     09:13:00       09:18:00
342  2026-03-09 09:23:40     6     09:23:00       09:24:00
345  2026-03-09 09:23:40     6     09:22:00       09:27:00

In [37]:
def convert_to_minutes(time_obj):
    return time_obj.hour * 60 + time_obj.minute
df_6_cleaned["planned_time_minutes"] = df_6_cleaned["planned_time"].apply(convert_to_minutes)
df_6_cleaned["estimated_time_minutes"] = df_6_cleaned["estimated_time"].apply(convert_to_minutes)
df_6_cleaned.head()

,collected_at,line,planned_time,estimated_time,planned_time_minutes,estimated_time_minutes
0,2026-03-09 06:33:25,6,06:31:00,06:33:00,391,393
10,2026-03-09 06:38:26,6,06:19:00,06:38:00,379,398
11,2026-03-09 06:38:26,6,06:35:00,06:39:00,395,399
30,2026-03-09 06:48:27,6,06:43:00,06:48:00,403,408
33,2026-03-09 06:48:27,6,06:48:00,06:50:00,408,410

In [ ]:
# Calculate delay in minutes
df_6_cleaned["delay_minutes"] = df_6_cleaned["estimated_time_minutes"] - df_6_cleaned["planned_time_minutes"]
df_6_cleaned.head()
df_6 = df_6_cleaned.drop(columns=["collected_at", "planned_time_minutes", "estimated_time_minutes", "estimated_time", "planned_time"])
df_6

In [ ]:
def convert_to_minutes(time_obj):
    return time_obj.hour * 60 + time_obj.minute

def clean_line(data, *line_numbers):
    df_line = data[data["line"].isin(line_numbers)].copy()
    df_line = df_line.drop_duplicates(subset=["line", "planned_time"], keep="last")
    df_line["planned_time_minutes"] = df_line["planned_time"].apply(convert_to_minutes)
    df_line["estimated_time_minutes"] = df_line["estimated_time"].apply(convert_to_minutes)
    df_line["delay_minutes"] = df_line["estimated_time_minutes"] - df_line["planned_time_minutes"]
    df_line = df_line.drop(columns=["collected_at", "planned_time_minutes", "estimated_time_minutes"])
    label = "_".join(str(n) for n in line_numbers)
    df_line.to_csv(f"data/line_{label}_cleaned.csv", index=False)
    return df_line

In [57]:
keep = (6, 64)
naser = pd.read_csv("/Users/edwind/Desktop/statinf_project/python_code/data/data.csv")
naser = naser[naser["line"].isin(keep)]
naser

,collected_at,line,transport_mode,planned_time,estimated_time
0,2026-03-09 06:33:25,6,Spårvagn,2026-03-09T06:31:00.0000000+01:00,2026-03-09T06:33:00.0000000+01:00
1,2026-03-09 06:33:25,64,Spårvagn,2026-03-09T06:28:00.0000000+01:00,2026-03-09T06:35:00.0000000+01:00
3,2026-03-09 06:33:25,64,Spårvagn,2026-03-09T06:36:00.0000000+01:00,2026-03-09T06:35:00.0000000+01:00
4,2026-03-09 06:33:25,6,Spårvagn,2026-03-09T06:19:00.0000000+01:00,2026-03-09T06:36:00.0000000+01:00
10,2026-03-09 06:38:26,6,Spårvagn,2026-03-09T06:19:00.0000000+01:00,2026-03-09T06:38:00.0000000+01:00
...,...,...,...,...,...
339,2026-03-09 09:18:39,6,Spårvagn,2026-03-09T09:23:00.0000000+01:00,2026-03-09T09:24:00.0000000+01:00
342,2026-03-09 09:23:40,6,Spårvagn,2026-03-09T09:23:00.0000000+01:00,2026-03-09T09:24:00.0000000+01:00
344,2026-03-09 09:23:40,64,Spårvagn,2026-03-09T09:25:00.0000000+01:00,2026-03-09T09:25:00.0000000+01:00
345,2026-03-09 09:23:40,6,Spårvagn,2026-03-09T09:22:00.0000000+01:00,2026-03-09T09:27:00.0000000+01:00
347,2026-03-09 09:23:40,64,Spårvagn,2026-03-09T09:29:00.0000000+01:00,2026-03-09T09:29:00.0000000+01:00

In [49]:
keep = (6, 64)
df_cleaned = df[df["line"].isin(keep)] # keep only rows with line 6 or line 64
df_cleaned

            collected_at  line planned_time estimated_time
0    2026-03-09 06:33:25     6     06:31:00       06:33:00
1    2026-03-09 06:33:25    64     06:28:00       06:35:00
3    2026-03-09 06:33:25    64     06:36:00       06:35:00
4    2026-03-09 06:33:25     6     06:19:00       06:36:00
10   2026-03-09 06:38:26     6     06:19:00       06:38:00
..                   ...   ...          ...            ...
339  2026-03-09 09:18:39     6     09:23:00       09:24:00
342  2026-03-09 09:23:40     6     09:23:00       09:24:00
344  2026-03-09 09:23:40    64     09:25:00       09:25:00
345  2026-03-09 09:23:40     6     09:22:00       09:27:00
347  2026-03-09 09:23:40    64     09:29:00       09:29:00

[112 rows x 4 columns]

In [54]:
keep = (6, 64)
clean_line(df_cleaned, *keep)

     line planned_time estimated_time  delay_minutes
0       6     06:31:00       06:33:00              2
1      64     06:28:00       06:35:00              7
3      64     06:36:00       06:35:00             -1
10      6     06:19:00       06:38:00             19
11      6     06:35:00       06:39:00              4
..    ...          ...            ...            ...
334    64     09:19:00       09:19:00              0
342     6     09:23:00       09:24:00              1
344    64     09:25:00       09:25:00              0
345     6     09:22:00       09:27:00              5
347    64     09:29:00       09:29:00              0

[68 rows x 4 columns]

In [55]:
df = pd.read_csv("/Users/edwind/Desktop/statinf_project/python_code/data/line_6_64_cleaned.csv")
df

    line planned_time estimated_time  delay_minutes
0      6     06:31:00       06:33:00              2
1     64     06:28:00       06:35:00              7
2     64     06:36:00       06:35:00             -1
3      6     06:19:00       06:38:00             19
4      6     06:35:00       06:39:00              4
..   ...          ...            ...            ...
63    64     09:19:00       09:19:00              0
64     6     09:23:00       09:24:00              1
65    64     09:25:00       09:25:00              0
66     6     09:22:00       09:27:00              5
67    64     09:29:00       09:29:00              0

[68 rows x 4 columns]